module.exports = {
  LOGIN_ALREADY_IN_USE: 'LOGIN_ALREADY_IN_USE',
  INVALID_LOGIN_CREDENTIALS: 'INVALID_LOGIN_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TASK_NOT_ELIGIBLE_FOR_EDITING: 'TASK_NOT_ELIGIBLE_FOR_EDITING'
}